image: alpine
stages:
    - test
test:
    image: docker
    services: 
        - name: docker:20-dind
          alias: docker
          command: ["--tls=false"]
    stage: test
    script:
        - sleep 5
        - echo "hello gitlab-ci"
    tags: 
        - docker-runner